### ISSUE TITLE
None type object has no mean

### ISSUE THREAD

**Issue by rishabhjoshi** [dayihengliu/CRQDA#1]
Hi, I trained a MRC model for SQuAD 1 dataset. After that, I wanted to train the AE model, however at line:
https://github.com/dayihengliu/CRQDA/blob/master/crqda/ae_train.py#L227
you're passing inputs, which does not contain "input_ids".
Then you have a check for "is not None" here : https://github.com/dayihengliu/CRQDA/blob/master/crqda/dag_model.py#L39.

I believe that it should be "is None" otherwise emb is None and the model will give None object has no mean error.

**Comment by rishabhjoshi** [comment]
Also, here : https://github.com/dayihengliu/CRQDA/blob/master/crqda/dag_model.py#L23, You pass 1024 as size, but Roberta has embedding size 768. 

Using this as is gives : RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 2

**Comment by dayihengliu** [comment]
> Also, here : https://github.com/dayihengliu/CRQDA/blob/master/crqda/dag_model.py#L23, You pass 1024 as size, but Roberta has embedding size 768.
> 
> Using this as is gives : RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 2

We use RoBERTa-large as the pre-trained MRC model by default. If you want to use the RoBERTa-based model as the pre-trained MRC model, you should change the word embedding size of the autoencoder from 1024 to 768.

**Comment by rishabhjoshi** [comment]
Yeah. That makes sense. Maybe you can add it to the readme as well. Currently, it just states a "roberta" model. Also, let me know your thoughts about the "is None" issue i described above.
