### ISSUE TITLE
utils file doesn't exist

### ISSUE THREAD

**Issue by rishabhjoshi** [dayihengliu/CRQDA#2]
This line imports a file that doesn't exist : https://github.com/dayihengliu/CRQDA/blob/master/crqda/inference.py#L91

**Comment by dayihengliu** [comment]
> This line imports a file that doesn't exist : https://github.com/dayihengliu/CRQDA/blob/master/crqda/inference.py#L91

Thanks, this is a test file and does not need to be used, so we deleted it.
