### ISSUE TITLE
Inference file doesn't dump the data in the correct format

### ISSUE THREAD

**Issue by rishabhjoshi** [dayihengliu/CRQDA#3]
Hi, I tried running the inference file, however, it just dumps a dict of questions that it generated. There is no answer / original question / context dumped. How do we map it back to original answers / questions so that we can create a dataset that we can finetune on?

**Comment by dayihengliu** [comment]
> Hi, I tried running the inference file, however, it just dumps a dict of questions that it generated. There is no answer / original question / context dumped. How do we map it back to original answers / questions so that we can create a dataset that we can finetune on?

Looks like you have solved this problem?  According to the format of the original dataset (json file), you can use json.dumps to add the augmented data to the original dataset
